# kitchen
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitchen
  namespace: go-coffeeshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kitchen
  template:
    metadata:
      labels:
        app: kitchen
    spec:
      containers:
      - name: kitchen
        image: ntthuan0106job/thuan-opswat-training:go-coffeeshop-kitchen-latest
        env:
        - name: APP_NAME
          value: kitchen-svc
        - name: IN_DOCKER
          value: "true"
        - name: PG_URL
          valueFrom:
            secretKeyRef:
              name: postgres
              key: PG_URL
        - name: PG_DSN_URL
          valueFrom:
            secretKeyRef:
              name: postgres
              key: PG_DSN_URL
        - name: RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: RABBITMQ_URL
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: private-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: kitchen
  namespace: go-coffeeshop
spec:
  ports:
  - name: kitchen-port
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: kitchen
