# rabbitmq
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: go-coffeeshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.11-management-alpine
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: RABBITMQ_DEFAULT_USER
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: RABBITMQ_DEFAULT_PASS
        ports:
        - containerPort: 5672
        - containerPort: 15672
        readinessProbe:
          exec:
            command: [ "rabbitmq-diagnostics", "-q", "ping" ]
          initialDelaySeconds: 10
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: go-coffeeshop
spec:
  ports:
  - name: rabbitmq-port-1
    protocol: TCP
    port: 5672
    targetPort: 5672
  - name: rabbitmq-port-2
    protocol: TCP
    port: 15672
    targetPort: 15672
  selector:
    app: rabbitmq
